// Copyright (c) 2020, Brandon Lehmann
//
// Redistribution and use in source and binary forms, with or without modification, are
// permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this list of
//    conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice, this list
//    of conditions and the following disclaimer in the documentation and/or other
//    materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors may be
//    used to endorse or promote products derived from this software without specific
//    prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
// THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
// THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef CRYPTO_SEED_T
#define CRYPTO_SEED_T

#include <encoding/languages/language.h>
#include <types/crypto_point_t.h>
#include <types/crypto_scalar_t.h>

struct crypto_seed_t final : SerializablePod<32>
{
  public:
    crypto_seed_t() = default;

    crypto_seed_t(std::initializer_list<unsigned char> input);

    explicit crypto_seed_t(const std::vector<unsigned char> &input);

    explicit crypto_seed_t(const std::string &s);

    JSON_STRING_CONSTRUCTOR(crypto_seed_t, fromJSON)

    /**
     * Generates a random seed with random entropy
     *
     * @param bits
     * @return
     */
    static crypto_seed_t random(size_t bits = 256);

    /**
     * Generates a random seed with entropy
     *
     * @param entropy
     * @return
     */
    static crypto_seed_t random(const std::vector<unsigned char> &entropy, size_t bits = 256);

    /**
     * Recovers a seed from a vector of words
     *
     * @param words
     * @param language
     * @return
     */
    static crypto_seed_t recover(
        const std::vector<std::string> &words,
        const Crypto::Mnemonics::Language::Language &language = Crypto::Mnemonics::Language::Language::ENGLISH);

    /**
     * Recovers a seed from a string of words
     *
     * @param phrase
     * @param language
     * @return
     */
    static crypto_seed_t recover(
        const std::string &phrase,
        const Crypto::Mnemonics::Language::Language &language = Crypto::Mnemonics::Language::Language::ENGLISH);

    /**
     * Generates deterministic subwallet keys from the wallet seed value.
     *
     * For compatibility & security purposes, all wallet keys and addresses, should be derived from
     * the wallet seed and the seed should never be used directly.
     *
     * Subwallets are generated by injecting deterministic salt into the hashing process
     * whereby it is nearly impossible to reconstruct the spend keys without knowing the
     * subwallet index and the seed value that they were derived from.
     *
     * @param wallet_index
     * @return
     */
    [[nodiscard]] std::tuple<crypto_public_key_t, crypto_secret_key_t> spend_keys(uint64_t wallet_index = 0) const;

    /**
     * Returns the timestamp the seed was created
     *
     * @return
     */
    [[nodiscard]] uint64_t timestamp() const;

    /**
     * Converts the seed to mnemonic phrase of words
     *
     * @param language
     * @return
     */
    [[nodiscard]] std::string to_mnemonic_phrase(
        const Crypto::Mnemonics::Language::Language &language = Crypto::Mnemonics::Language::Language::ENGLISH) const;

    /**
     * Converts the seed to a vector of mnemonic words
     *
     * @param language
     * @return
     */
    [[nodiscard]] std::vector<std::string> to_mnemonic_words(
        const Crypto::Mnemonics::Language::Language &language = Crypto::Mnemonics::Language::Language::ENGLISH) const;

    /**
     * Calculates deterministic wallet view keys from the given wallet seed value.
     *
     * For compatibility & security purposes, all wallet keys and addresses, should be derived from
     * the wallet seed and the seed should never be used directly.
     *
     * @return
     */
    [[nodiscard]] std::tuple<crypto_public_key_t, crypto_secret_key_t> view_keys() const;

  private:
    [[nodiscard]] bool is_128_bit() const;
};

#endif
